name: Deploy DigiCryptoMarket

on:
  push:
    branches:
      - master  # Trigger on push to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}        # Server IP
        username: bitnami                          # SSH username
        key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}  # Private key from Secrets
        port: 22                                   # SSH port
        script: |
          cd ../../bitnami/wordpress/wp-content/themes
          git reset --hard
          git pull origin master
